markdown: kramdown

analytics :
  provider : google
  google :
      tracking_id : 'UA-48554146-1'


permalink: /:year/:month/:title/
url: http://xiaodongyang.org
author: Xiaodong Yang
pygments: true
